import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const outPath = path.join(process.cwd(), '.env.production.local');

const randomSecret = () => crypto.randomBytes(32).toString('hex');

const defaults: Record<string, string> = {
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || 'sk-replace-me',
  OPENAI_MODEL_PRIMARY: 'gpt-5',
  OPENAI_MODEL_FAST: 'gpt-5-mini',
  OPENAI_MODEL_TRANSCRIBE: 'gpt-4o-mini-transcribe',
  OPENAI_MODEL_EMBED: 'text-embedding-3-small',
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL || 'https://replace-me.upstash.io',
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN || 'replace-me',
  DATABASE_URL:
    process.env.DATABASE_URL || 'postgresql://beast_mode:replace-me@127.0.0.1:5432/beast_mode',
  AUTH_SECRET: process.env.AUTH_SECRET || randomSecret(),
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET || randomSecret(),
  BEAST_MODE_ALPHA_AUTH_PASSWORD: process.env.BEAST_MODE_ALPHA_AUTH_PASSWORD || randomSecret(),
  BEAST_MODE_TIER: 'free',
  BEAST_MODE_DAILY_AI_BUDGET_USD: '2',
  BEAST_MODE_MONTHLY_AI_BUDGET_USD: '30',
  AI_ENABLE_WORKOUT_PLAN: 'true',
  AI_ENABLE_LIVE_COACH: 'true',
  AI_ENABLE_POST_WORKOUT: 'true',
  AI_ENABLE_RISK_ANALYSIS: 'true',
  AI_ENABLE_LOG_PARSER: 'true',
  AI_ENABLE_TRANSCRIBE: 'true',
  AI_ENABLE_PROGRESSION_PLAN: 'true',
  FEATURE_TELEMETRY_INGEST: 'true',
  FEATURE_CLOUD_SYNC_ALPHA: 'true',
  FEATURE_PROGRESSION_AUTOPILOT: 'true',
  FEATURE_RETENTION_LOOPS: 'true',
  FEATURE_HEALTH_INTEGRATIONS: 'true',
  FEATURE_MONETIZATION_CONTROLS: 'true',
  TELEMETRY_EXPORT_URL: process.env.TELEMETRY_EXPORT_URL || '',
  TELEMETRY_EXPORT_TOKEN: process.env.TELEMETRY_EXPORT_TOKEN || '',
  TELEMETRY_EXPORT_MIN_INTERVAL_MS: '30000',
  OURA_API_BASE_URL: 'https://api.oura.com/v2/usercollection',
};

const existing = new Map<string, string>();
if (fs.existsSync(outPath)) {
  const current = fs.readFileSync(outPath, 'utf8');
  for (const line of current.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx <= 0) continue;
    existing.set(trimmed.slice(0, idx), trimmed.slice(idx + 1));
  }
}

const merged = { ...defaults };
existing.forEach((value, key) => {
  merged[key] = value;
});

const lines = [
  '# Generated by npm run env:bootstrap:prod',
  '# Replace placeholder values before real production deployment.',
  ...Object.entries(merged).map(([key, value]) => `${key}=${value}`),
  '',
];

fs.writeFileSync(outPath, lines.join('\n'));
console.log(`Wrote ${outPath}`);
